#! /bin/bash
dasio=~/SW/dasng/git/libs/dasio/src
dasiosrc="$dasio/appid.cc
  $dasio/loop.cc
  $dasio/nldbg.c
  $dasio/not_parsed.cc
  $dasio/server.cc
  $dasio/ascii_escape.cc
  $dasio/socket.cc
  $dasio/client.cc
  $dasio/msg.cc
  $dasio/timeout.cc
  $dasio/unix_name.cc
  $dasio/interface.cc"

nl=~/SW/dasng/git/libs/nl
nlsrc="$nl/nl.h
  $nl/newmem.c
  $nl/nlresp.c
  $nl/nl_assert.h
  $nl/nl_verr.c
  $nl/nl_error.c"

oui=/usr/local/include/oui.h

srcs="BBB/Makefile
POPS_srvr.cc
POPS_srvroui.cc
POPS_srvr.h"

dest=pops:SW/srvr
scp $dasiosrc $nlsrc $oui $srcs $dest
scp $dasio/dasio/*.h $dest/dasio
