function pdpgshkt(varargin)
% pdpgshkt( [...] );
% HK Temp
h = timeplot({'POPS_Temp','Amb_T','PPmpT'}, ...
      'HK Temp', ...
      'Temp', ...
      {'POPS\_Temp','Amb\_T','PPmpT'}, ...
      varargin{:} );
