function pdpopsdacsaaics(varargin);
% pdpopsdacsaaics( [...] );
% uDACS A AI Ch S
h = ne_dstat({
  'Reset', 'uDACS_A_stat0', 3; ...
	'MSat0', 'uDACS_A_stat0', 2; ...
	'FSat0', 'uDACS_A_stat0', 1; ...
	'OUV0', 'uDACS_A_stat0', 0; ...
	'MSat1', 'uDACS_A_stat1', 2; ...
	'FSat1', 'uDACS_A_stat1', 1; ...
	'OUV1', 'uDACS_A_stat1', 0; ...
	'MSat2', 'uDACS_A_stat2', 2; ...
	'FSat2', 'uDACS_A_stat2', 1; ...
	'OUV2', 'uDACS_A_stat2', 0; ...
	'MSat3', 'uDACS_A_stat3', 2; ...
	'FSat3', 'uDACS_A_stat3', 1; ...
	'OUV3', 'uDACS_A_stat3', 0; ...
	'MSat4', 'uDACS_A_stat4', 2; ...
	'FSat4', 'uDACS_A_stat4', 1; ...
	'OUV4', 'uDACS_A_stat4', 0; ...
	'MSat5', 'uDACS_A_stat5', 2; ...
	'FSat5', 'uDACS_A_stat5', 1; ...
	'OUV5', 'uDACS_A_stat5', 0; ...
	'MSat6', 'uDACS_A_stat6', 2; ...
	'FSat6', 'uDACS_A_stat6', 1; ...
	'OUV6', 'uDACS_A_stat6', 0; ...
	'MSat7', 'uDACS_A_stat7', 2; ...
	'FSat7', 'uDACS_A_stat7', 1; ...
	'OUV7', 'uDACS_A_stat7', 0 }, 'AI Ch S', varargin{:} );
