function pdpopsanccm(varargin);
% pdpopsanccm( [...] );
% Alicat nccm
h = timeplot({'BMFC_Set','BMFC_MassFlow','PMFC_Set','PMFC_MassFlow','SMFC_Set','SMFC_MassFlow'}, ...
      'Alicat nccm', ...
      'nccm', ...
      {'BMFC\_Set','BMFC\_MassFlow','PMFC\_Set','PMFC\_MassFlow','SMFC\_Set','SMFC\_MassFlow'}, ...
      varargin{:} );
