function pdpopsirt(varargin);
% pdpopsirt( [...] );
% Inlet Ring T
h = timeplot({'Ring1T','Ring2T','Ring3T','RingT'}, ...
      'Inlet Ring T', ...
      'Ring T', ...
      {'Ring1T','Ring2T','Ring3T','RingT'}, ...
      varargin{:} );
