function pdpopshhps_dp(varargin)
% pdpopshhps_dp( [...] );
% Honeywell HPS dP
h = timeplot({'HPS_dP'}, ...
      'Honeywell HPS dP', ...
      'HPS dP', ...
      {'HPS\_dP'}, ...
      varargin{:} );
