function pdpopsrtcelapsed(varargin);
% pdpopsrtcelapsed( [...] );
% RTC elapsed
h = timeplot({'uDACS_A_elapsed','uDACS_B_elapsed'}, ...
      'RTC elapsed', ...
      'elapsed', ...
      {'uDACS\_A\_elapsed','uDACS\_B\_elapsed'}, ...
      varargin{:} );
