function pdpopslfeg(varargin);
% pdpopslfeg( [...] );
% LFE Gains
h = timeplot({'LFE_PGain','LFE_IGain'}, ...
      'LFE Gains', ...
      'Gains', ...
      {'LFE\_PGain','LFE\_IGain'}, ...
      varargin{:} );
