function pdpopsalicatnccm(varargin);
% pdpopsalicatnccm( [...] );
% Alicat nccm
h = timeplot({'BMFC_Set','BMFC_MassFlow','PMFC_Set','PMFC_MassFlow','MMFC_Set','MMFC_MassFlow'}, ...
      'Alicat nccm', ...
      'nccm', ...
      {'BMFC\_Set','BMFC\_MassFlow','PMFC\_Set','PMFC\_MassFlow','MMFC\_Set','MMFC\_MassFlow'}, ...
      varargin{:} );
