function pdpopsiv(varargin)
% pdpopsiv( [...] );
% Inlet Velocity
h = timeplot({'PD_Vel','Pitot_Vel'}, ...
      'Inlet Velocity', ...
      'Velocity', ...
      {'PD\_Vel','Pitot\_Vel'}, ...
      varargin{:} );
