function pdpopshs(varargin);
% pdpopshs( [...] );
% Honeywell Status
h = ne_dstat({
  'PS1_Init', 'HPS_Stat', 0; ...
	'PS1_CRC_OK', 'HPS_Stat', 1; ...
	'PS2_Init', 'HPS_Stat', 2; ...
	'PS2_CRC_OK', 'HPS_Stat', 3; ...
	'PS3_Init', 'HPS_Stat', 4; ...
	'PS3_CRC_OK', 'HPS_Stat', 5 }, 'Status', varargin{:} );
