function pdpopsdacsbhps_dp(varargin);
% pdpopsdacsbhps_dp( [...] );
% uDACS B HPS dP
h = timeplot({'HPS_dP'}, ...
      'uDACS B HPS dP', ...
      'HPS dP', ...
      {'HPS\_dP'}, ...
      varargin{:} );
