function pdpopshhpsp(varargin)
% pdpopshhpsp( [...] );
% Honeywell HPS P
h = timeplot({'HPS_P','HPS3_P'}, ...
      'Honeywell HPS P', ...
      'HPS P', ...
      {'HPS\_P','HPS3\_P'}, ...
      varargin{:} );
