function pdpopsdacsaai(varargin);
% pdpopsdacsaai( [...] );
% uDACS A AI errs
h = timeplot({'uDACS_A_errors'}, ...
      'uDACS A AI errs', ...
      'AI errs', ...
      {'uDACS\_A\_errors'}, ...
      varargin{:} );
