function pdpopsahks(varargin)
% pdpopsahks( [...] );
% Alicat HK Status
h = timeplot({'BMFC_Status','PMFC_Status','MMFC_Status'}, ...
      'Alicat HK Status', ...
      'Status', ...
      {'BMFC\_Status','PMFC\_Status','MMFC\_Status'}, ...
      varargin{:} );
