function pdpopsattitudeaz(varargin);
% pdpopsattitudeaz( [...] );
% Attitude AZ
h = timeplot({'Sun_Az_AC'}, ...
      'Attitude AZ', ...
      'AZ', ...
      {'Sun\_Az\_AC'}, ...
      varargin{:} );
