function pdpopspopsstale(varargin);
% pdpopspopsstale( [...] );
% POPS Stale
h = timeplot({'POPS_Stale','POPS_DrvStale'}, ...
      'POPS Stale', ...
      'Stale', ...
      {'POPS\_Stale','POPS\_DrvStale'}, ...
      varargin{:} );
