function pdpopsrtcloop(varargin);
% pdpopsrtcloop( [...] );
% RTC loop
h = timeplot({'uDACS_A_curloopdur','uDACS_A_maxloopdur','uDACS_B_curloopdur','uDACS_B_maxloopdur'}, ...
      'RTC loop', ...
      'loop', ...
      {'uDACS\_A\_curloopdur','uDACS\_A\_maxloopdur','uDACS\_B\_curloopdur','uDACS\_B\_maxloopdur'}, ...
      varargin{:} );
