function pdpopspopsldm(varargin);
% pdpopspopsldm( [...] );
% POPS LD Mon
h = timeplot({'POPS_LD_Mon'}, ...
      'POPS LD Mon', ...
      'LD Mon', ...
      {'POPS\_LD\_Mon'}, ...
      varargin{:} );
