function pdpopspopsnum_cc(varargin)
% pdpopspopsnum_cc( [...] );
% POPS num cc
h = timeplot({'POPS_num_cc'}, ...
      'POPS num cc', ...
      'num cc', ...
      {'POPS\_num\_cc'}, ...
      varargin{:} );
