function pdpopspopshkldt(varargin)
% pdpopspopshkldt( [...] );
% POPS HK LD Temp
h = timeplot({'POPS_LDTemp'}, ...
      'POPS HK LD Temp', ...
      'LD Temp', ...
      {'POPS\_LDTemp'}, ...
      varargin{:} );
