function pdpopsiwg1_stattd(varargin)
% pdpopsiwg1_stattd( [...] );
% IWG1 Stat T Drift
h = timeplot({'TDDrift','TDrift'}, ...
      'IWG1 Stat T Drift', ...
      'T Drift', ...
      {'TDDrift','TDrift'}, ...
      varargin{:} );
