function pdpopsdacsbais(varargin);
% pdpopsdacsbais( [...] );
% uDACS B AI Stat
h = timeplot({'uDACS_B_status'}, ...
      'uDACS B AI Stat', ...
      'AI Stat', ...
      {'uDACS\_B\_status'}, ...
      varargin{:} );
