function pdpopsalicatccm(varargin);
% pdpopsalicatccm( [...] );
% Alicat ccm
h = timeplot({'BMFC_VolFlow','PMFC_VolFlow'}, ...
      'Alicat ccm', ...
      'ccm', ...
      {'BMFC\_VolFlow','PMFC\_VolFlow'}, ...
      varargin{:} );
