function pdpopsdacsbdac(varargin);
% pdpopsdacsbdac( [...] );
% uDACS B DAC
h = timeplot({'uDACS_B_VSet1'}, ...
      'uDACS B DAC', ...
      'DAC', ...
      {'uDACS\_B\_VSet1'}, ...
      varargin{:} );
