function pdpopshhpst(varargin);
% pdpopshhpst( [...] );
% Honeywell HPS T
h = timeplot({'HPS1_Temp','HPS2_Temp'}, ...
      'Honeywell HPS T', ...
      'HPS T', ...
      {'HPS1\_Temp','HPS2\_Temp'}, ...
      varargin{:} );
