function pdpopsaccm(varargin);
% pdpopsaccm( [...] );
% Alicat ccm
h = timeplot({'MFC1_Set','MFC1_VolFlow','MFC2_Set','MFC2_VolFlow'}, ...
      'Alicat ccm', ...
      'ccm', ...
      {'MFC1\_Set','MFC1\_VolFlow','MFC2\_Set','MFC2\_VolFlow'}, ...
      varargin{:} );
