function pdpopsdacsas(varargin);
% pdpopsdacsas( [...] );
% uDACS A Status
h = timeplot({'uDACS_A_status'}, ...
      'uDACS A Status', ...
      'Status', ...
      {'uDACS\_A\_status'}, ...
      varargin{:} );
