function pdpopsahkt(varargin);
% pdpopsahkt( [...] );
% Alicat HK T
h = timeplot({'BMFC_T','PMFC_T','SMFC_T'}, ...
      'Alicat HK T', ...
      'T', ...
      {'BMFC\_T','PMFC\_T','SMFC\_T'}, ...
      varargin{:} );
