function pdpopsamf(varargin)
% pdpopsamf( [...] );
% Algo M Ffilt
h = timeplot({'BMFC_MassFlow','BMFC_MF_LP'}, ...
      'Algo M Ffilt', ...
      'M Ffilt', ...
      {'BMFC\_MassFlow','BMFC\_MF\_LP'}, ...
      varargin{:} );
