function pdpopshhpsp(varargin);
% pdpopshhpsp( [...] );
% Honeywell HPS P
h = timeplot({'InltBP','HPS_P'}, ...
      'Honeywell HPS P', ...
      'HPS P', ...
      {'InltBP','HPS\_P'}, ...
      varargin{:} );
