function pdpopsdacsbr(varargin);
% pdpopsdacsbr( [...] );
% uDACS B Raw
h = timeplot({'uDACS_B_Raw1','uDACS_B_Raw2','uDACS_B_Raw3'}, ...
      'uDACS B Raw', ...
      'Raw', ...
      {'uDACS\_B\_Raw1','uDACS\_B\_Raw2','uDACS\_B\_Raw3'}, ...
      varargin{:} );
