function pdpopsdacsbain(varargin)
% pdpopsdacsbain( [...] );
% uDACS B AI N
h = timeplot({'uDACS_B_N'}, ...
      'uDACS B AI N', ...
      'AI N', ...
      {'uDACS\_B\_N'}, ...
      varargin{:} );
