function pdpopsdacsah(varargin);
% pdpopsdacsah( [...] );
% uDACS A Hdrs
h = timeplot({'uDACS_A_stat0','uDACS_A_stat1','uDACS_A_stat2','uDACS_A_stat3','uDACS_A_stat4','uDACS_A_stat5','uDACS_A_stat6','uDACS_A_stat7'}, ...
      'uDACS A Hdrs', ...
      'Hdrs', ...
      {'uDACS\_A\_stat0','uDACS\_A\_stat1','uDACS\_A\_stat2','uDACS\_A\_stat3','uDACS\_A\_stat4','uDACS\_A\_stat5','uDACS\_A\_stat6','uDACS\_A\_stat7'}, ...
      varargin{:} );
