function pdpopsasccm(varargin);
% pdpopsasccm( [...] );
% Alicat sccm
h = timeplot({'MFC1_MassFlow','MFC2_MassFlow'}, ...
      'Alicat sccm', ...
      'sccm', ...
      {'MFC1\_MassFlow','MFC2\_MassFlow'}, ...
      varargin{:} );
