function pdpopsdacsbhpst(varargin);
% pdpopsdacsbhpst( [...] );
% uDACS B HPS T
h = timeplot({'HPS1_Temp','HPS2_Temp'}, ...
      'uDACS B HPS T', ...
      'HPS T', ...
      {'HPS1\_Temp','HPS2\_Temp'}, ...
      varargin{:} );
