function pdpopsahkstale(varargin)
% pdpopsahkstale( [...] );
% Alicat HK Stale
h = timeplot({'BMFC_Stale','PMFC_Stale','MMFC_Stale','Alicat_Stale'}, ...
      'Alicat HK Stale', ...
      'Stale', ...
      {'BMFC\_Stale','PMFC\_Stale','MMFC\_Stale','Alicat\_Stale'}, ...
      varargin{:} );
