function pdpopsps(varargin);
% pdpopsps( [...] );
% Pumps Status
h = ne_dstat({
  'PPmpCmd', 'PumpsStat', 0; ...
	'PPmpS', 'PumpsStat', 1; ...
	'BPmpCmd', 'PumpsStat', 2; ...
	'BPmpS', 'PumpsStat', 0 }, 'Status', varargin{:} );
