function pdpopsdacsbai(varargin);
% pdpopsdacsbai( [...] );
% uDACS B AI errs
h = timeplot({'uDACS_B_errors'}, ...
      'uDACS B AI errs', ...
      'AI errs', ...
      {'uDACS\_B\_errors'}, ...
      varargin{:} );
