function pdpopsahkt(varargin)
% pdpopsahkt( [...] );
% Alicat HK T
h = timeplot({'BMFC_T','PMFC_T','MMFC_T'}, ...
      'Alicat HK T', ...
      'T', ...
      {'BMFC\_T','PMFC\_T','MMFC\_T'}, ...
      varargin{:} );
