function pdpopsdacsbaics(varargin);
% pdpopsdacsbaics( [...] );
% uDACS B AI Ch S
h = ne_dstat({
  'Reset', 'uDACS_B_stat0', 3; ...
	'MSat0', 'uDACS_B_stat0', 2; ...
	'FSat0', 'uDACS_B_stat0', 1; ...
	'OUV0', 'uDACS_B_stat0', 0; ...
	'MSat1', 'uDACS_B_stat1', 2; ...
	'FSat1', 'uDACS_B_stat1', 1; ...
	'OUV1', 'uDACS_B_stat1', 0; ...
	'MSat2', 'uDACS_B_stat2', 2; ...
	'FSat2', 'uDACS_B_stat2', 1; ...
	'OUV2', 'uDACS_B_stat2', 0; ...
	'MSat3', 'uDACS_B_stat3', 2; ...
	'FSat3', 'uDACS_B_stat3', 1; ...
	'OUV3', 'uDACS_B_stat3', 0 }, 'AI Ch S', varargin{:} );
