function pdpopsahkstale(varargin);
% pdpopsahkstale( [...] );
% Alicat HK Stale
h = timeplot({'BMFC_Stale','PMFC_Stale','SMFC_Stale','Alicat_Stale'}, ...
      'Alicat HK Stale', ...
      'Stale', ...
      {'BMFC\_Stale','PMFC\_Stale','SMFC\_Stale','Alicat\_Stale'}, ...
      varargin{:} );
