function pdpopsdacsadac(varargin);
% pdpopsdacsadac( [...] );
% uDACS A DAC
h = timeplot({'uDACS_A_VSet0','uDACS_A_VSet1','uDACS_A_VSet2','uDACS_A_VSet3'}, ...
      'uDACS A DAC', ...
      'DAC', ...
      {'uDACS\_A\_VSet0','uDACS\_A\_VSet1','uDACS\_A\_VSet2','uDACS\_A\_VSet3'}, ...
      varargin{:} );
