function pdpopsalicatnccm(varargin)
% pdpopsalicatnccm( [...] );
% Alicat nccm
h = timeplot({'BMFC_MassFlow','BMFC_Set','PMFC_MassFlow','PMFC_Set','MMFC_MassFlow','MMFC_Set'}, ...
      'Alicat nccm', ...
      'nccm', ...
      {'BMFC\_MassFlow','BMFC\_Set','PMFC\_MassFlow','PMFC\_Set','MMFC\_MassFlow','MMFC\_Set'}, ...
      varargin{:} );
