function pengpopsldt(varargin);
% pengpopsldt( [...] );
% POPS LD Temp
h = timeplot({'POPS_LDTemp'}, ...
      'POPS LD Temp', ...
      'LD Temp', ...
      {'POPS\_LDTemp'}, ...
      varargin{:} );
