function pengahkstale(varargin);
% pengahkstale( [...] );
% Alicat HK Stale
h = timeplot({'MFC1_Stale','MFC2_Stale','Alicat_Stale'}, ...
      'Alicat HK Stale', ...
      'Stale', ...
      {'MFC1\_Stale','MFC2\_Stale','Alicat\_Stale'}, ...
      varargin{:} );
