function pengaslm(varargin);
% pengaslm( [...] );
% Alicat slm
h = timeplot({'MFC1_Set','MFC1_VolFlow'}, ...
      'Alicat slm', ...
      'slm', ...
      {'MFC1\_Set','MFC1\_VolFlow'}, ...
      varargin{:} );
