function pengahks(varargin);
% pengahks( [...] );
% Alicat HK Status
h = timeplot({'MFC1_Status','MFC2_Status'}, ...
      'Alicat HK Status', ...
      'Status', ...
      {'MFC1\_Status','MFC2\_Status'}, ...
      varargin{:} );
