function pengaccm(varargin);
% pengaccm( [...] );
% Alicat ccm
h = timeplot({'MFC2_Set','MFC2_VolFlow'}, ...
      'Alicat ccm', ...
      'ccm', ...
      {'MFC2\_Set','MFC2\_VolFlow'}, ...
      varargin{:} );
