function ui_eng
f = ne_dialg('Engineering Data',1);
f = ne_dialg(f, 'add', 0, 1, 'gengtm', 'T Mbase' );
f = ne_dialg(f, 'add', 1, 0, 'pengtmtd', 'T Drift' );
f = ne_dialg(f, 'add', 1, 0, 'pengtmcpu', 'CPU' );
f = ne_dialg(f, 'add', 1, 0, 'pengtmram', 'RAM' );
f = ne_dialg(f, 'add', 1, 0, 'pengtmd', 'Disk' );
f = ne_dialg(f, 'add', 0, 1, 'gengahk', 'Alicat HK' );
f = ne_dialg(f, 'add', 1, 0, 'pengahks', 'Status' );
f = ne_dialg(f, 'add', 1, 0, 'pengahkstale', 'Stale' );
f = ne_dialg(f, 'add', 1, 0, 'pengahkt', 'T' );
f = ne_dialg(f, 'add', 1, 0, 'pengahkmbar', 'mbar' );
f = ne_dialg(f, 'add', 1, 0, 'pengahktorr', 'Torr' );
f = ne_dialg(f, 'add', 0, 1, 'genga', 'Alicat' );
f = ne_dialg(f, 'add', 1, 0, 'pengaslm', 'slm' );
f = ne_dialg(f, 'add', 1, 0, 'pengagps', 'gps' );
f = ne_dialg(f, 'add', 1, 0, 'pengaccm', 'ccm' );
f = ne_dialg(f, 'add', 1, 0, 'pengakgs', 'kgs' );
f = ne_listdirs(f, 'C:/home/Exp', 15);
f = ne_dialg(f, 'newcol');
ne_dialg(f, 'resize');
